@startuml

skinparam linetype polyline

abstract class Diagrama

package "Estructurales (fotos)" as estructurales {
  abstract class Estructural {
    // cosas tangibles
    // e intangibles
  }
  
  package "Básicos" {
    class Clases {
      // descripciones
    }
    class Objetos {
      // concreciones
      // con estado
    }
  }
  
  package "Implementación" {
    class Componentes {
      // software
      // desplegable
    }
    class Despliegue {
      // nodo
      // hardware
    }
  }
  
  class Paquetes {
    // agrupación
    // contextual
  }
  
  class "Estructura\nCompuesta" as EstructuraCompuesta
}

package "Comportamientos (videos)" as comportamientos {
  abstract class Comportamiento {
    // transformación
    // en el tiempo
  }
  
  class "Casos de Uso" as CasosUso {
    // sistema
    // como unidad
  }
  
  package "Flujo" {
    class Estados {
      // secuencia de
      // estados
    }
    class Actividad {
      // secuencia de
      // actividades
    }
  }
  
  abstract class Interacción {
    // con objeto emisor
    // y receptor
  }
  
  package "Mensajes" {
    class Comunicación {
      // colaboración de
      // mensajes
    }
    class Secuencia {
      // secuencia
      // con mensajes
    }
  }
  
  class "Interacción\nGeneral" as InteraccionGeneral
  class Tiempo
}

Diagrama <|-down- Estructural
Diagrama <|-down- Comportamiento

Estructural <|-down- Clases
Estructural <|-down- Objetos
Clases <|-down- Componentes
Clases <|-down- Despliegue
Estructural <|-down--- Paquetes
Estructural <|-down---- EstructuraCompuesta

Comportamiento <|-down- CasosUso
Comportamiento <|-down- Estados
Comportamiento <|-down- Actividad
Comportamiento <|-down-- Interacción

Interacción <|-down- Comunicación
Interacción <|-down- Secuencia
Interacción <|-down-- InteraccionGeneral
Interacción <|-down-- Tiempo

Clases -[hidden]right- Objetos
Componentes -[hidden]right- Despliegue
Estados -[hidden]right- Actividad
Comunicación -[hidden]right- Secuencia

@enduml